# Generated by Django 3.2.16 on 2023-01-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='memory_type',
            field=models.CharField(max_length=10),
        ),
    ]
