# Generated by Django 3.2.16 on 2023-01-22 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_gpu_memory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='base_clock',
            field=models.SmallIntegerField(default=0, verbose_name='Base Clock'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='boost_clock',
            field=models.SmallIntegerField(default=0, verbose_name='Boost Clock'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='content',
            field=models.TextField(verbose_name='GPU Information'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='date_released',
            field=models.DateField(default=datetime.date.today, verbose_name='Date Released'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='gpu_brand',
            field=models.IntegerField(choices=[(0, 'NVIDIA'), (1, 'AMD')], default=0, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='memory_size',
            field=models.IntegerField(choices=[(0, '4GB'), (1, '8GB'), (2, '12GB'), (3, '16GB'), (4, '20GB'), (5, '24GB'), (6, '48GB')], default=0, verbose_name='Memory Size'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='memory_type',
            field=models.CharField(max_length=10, verbose_name='Memory Type'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='GPU Name'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='specs',
            field=models.TextField(blank=True, verbose_name='Other Specs'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated On'),
        ),
    ]
