# Generated by Django 3.2.16 on 2023-01-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230122_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='base_clock',
            field=models.SmallIntegerField(default=0, verbose_name='Base Clock (MHz)'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='boost_clock',
            field=models.SmallIntegerField(default=0, verbose_name='Boost Clock (MHz)'),
        ),
    ]
