# Generated by Django 3.2.16 on 2023-01-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_gpu_sourced_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='brand',
            field=models.IntegerField(choices=[(0, 'NVIDIA'), (1, 'AMD'), (2, 'OTHER')], default=2, verbose_name='Current GPU'),
        ),
    ]
